/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoatMark: typeof import('./src/components/BoatMark.vue')['default']
    HeroBoat: typeof import('./src/components/HeroBoat.vue')['default']
    ProjectTree: typeof import('./src/components/ProjectTree.vue')['default']
    Reveal: typeof import('./src/components/Reveal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SailDivider: typeof import('./src/components/SailDivider.vue')['default']
    TerminalBlock: typeof import('./src/components/TerminalBlock.vue')['default']
    ThemeSelect: typeof import('./src/components/ThemeSelect.vue')['default']
  }
}
