name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.18.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:unit
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm stylelint:fix
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v6.10.9
        with:
          build: pnpm build
          start: pnpm dev
        env:
          CI: true
